// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567954348);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567954468);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1568347316);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1567954228);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567954108);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1567954709);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567954589);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567953959);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"1711\":[1567955170503]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{751646b5-dc7e-4de0-b956-ada13b4cbe06}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1567915200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1567955169);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 0);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.policies.runOncePerModification.setHomepage", "file:///usr/share/kali-defaults/web/homepage.html");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1568347313460");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1568350913460");
user_pref("browser.search.cohort", "apr18-1");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190709221323");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1568347313");
user_pref("browser.slowStartup.averageTime", 34782);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190709221323");
user_pref("browser.startup.homepage_override.mstone", "60.8.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "60.8.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Wed, 28 Aug 2019 19:55:12 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1567954351);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190709221323");
user_pref("extensions.lastAppVersion", "60.8.0");
user_pref("extensions.lastPlatformVersion", "60.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"ff879b30-82d3-45ea-80e8-9a8ca9230ab7\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1567954315);
user_pref("media.gmp-manager.buildID", "20190709221323");
user_pref("media.gmp-manager.lastCheck", 1567954012);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.identity.timeout", 1);
user_pref("media.peerconnection.turn.disable", true);
user_pref("media.peerconnection.use_document_iceservers", false);
user_pref("media.peerconnection.video.enabled", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1567954316);
user_pref("places.history.expiration.transient_current_max_pages", 59139);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "853f00a1-cc9f-4865-9f98-747ccd81eb2f");
user_pref("services.blocklist.addons.checked", 1567954482);
user_pref("services.blocklist.clock_skew_seconds", -13);
user_pref("services.blocklist.gfx.checked", 1567954482);
user_pref("services.blocklist.last_etag", "\"1567814407663\"");
user_pref("services.blocklist.last_update_seconds", 1567954482);
user_pref("services.blocklist.onecrl.checked", 1567954482);
user_pref("services.blocklist.pinning.checked", 1567954482);
user_pref("services.blocklist.plugins.checked", 1567954482);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1567954315);
user_pref("toolkit.startup.last_success", 1568347274);
user_pref("toolkit.telemetry.cachedClientID", "a1288813-a524-4ed4-9170-1242583f69b6");
user_pref("toolkit.telemetry.previousBuildID", "20190709221323");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
